export const BUSINESS = {
  name: "Ganpati Lifecare",
  alternateNames: ["Ganpati Life Care", "GLC", "Ganpati Life Care Hanumangarh", "Ganpati Lifecare Goluwala", "Ganpati Lifecare Sri Ganganagar", "Ganpati Lifecare Shri Ganganagar"],
  shortName: "GLC",
  owner: "Dharampal Verma",
  contactPerson: "Dharampal Verma",
  ownerTitle: "Founder & Owner — Dharampal Verma",
  location: "Goluwala, Hanumangarh, Rajasthan, India",
  address: {
    streetAddress: "Goluwala",
    addressLocality: "Hanumangarh",
    addressRegion: "Rajasthan",
    postalCode: "335512",
    addressCountry: "IN",
  },
  phones: ["+919828232254", "+919460095250"] as const,
  phoneDisplay: ["+91 98282 32254", "+91 94600 95250"] as const,
  email: "whiteroseglc@gmail.com",
  whatsapp: "919828232254",
  mapQuery: "Goluwala, Hanumangarh, Rajasthan, India",
  directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=Goluwala+Hanumangarh+Rajasthan+India",
  siteUrl: "https://ganpatilifecare.vercel.app",
} as const;

export const NAV_LINKS = [
  { href: "/#home", label: "Home" },
  { href: "/#about", label: "About" },
  { href: "/#products", label: "Products" },
  { href: "/#categories", label: "Categories" },
  { href: "/#why-us", label: "Why Choose Us" },
  { href: "/#testimonials", label: "Testimonials" },
  { href: "/#contact", label: "Contact" },
] as const;

export const SEO_KEYWORDS = [
  "Ganpati Lifecare",
  "Ganpati Life Care",
  "Ganpati Lifecare Hanumangarh",
  "Ganpati Life Care Hanumangarh",
  "Ganpati Lifecare Goluwala",
  "Ganpati Life Care Goluwala",
  "Ganpati Lifecare Sri Ganganagar",
  "Dharampal Verma",
  "medical supplier in Hanumangarh",
  "medical supplier Shri Ganganagar",
  "surgical products supplier Shri Ganganagar",
  "surgical products Rajasthan",
  "orthopedic products Rajasthan",
  "orthopedic supplier Rajasthan",
  "hospital consumables Rajasthan",
  "medical supplies Hanumangarh",
  "hospital supplies Rajasthan",
  "hospital uniforms Rajasthan",
  "Orthocot Cotton Roll supplier",
  "Cotton roll supplier India",
  "Stockinet supplier",
  "Goluwala Rajasthan healthcare supplies",
  "North Rajasthan medical supplies",
] as const;
