@echo off
title GLC Auto Sync Loop
echo Starting Ganpati Lifecare GitHub Auto-Sync (Every 5 minutes)...
:loop
echo [%date% %time%] Staging files...
git add .
echo [%date% %time%] Committing changes...
git commit -m "Auto sync"
echo [%date% %time%] Pushing to GitHub...
git push origin main
echo [%date% %time%] Waiting for 300 seconds before next sync...
timeout /t 300
goto loop
